// Mock data generator for tasks
export const generateMockTasks = () => [
  {
    id: "task-1",
    title: "Document experiment results",
    description: "Complete documentation for recent experiment findings",
    status: "completed",
    priority: "low",
    assigneeId: "2",
    experimentId: "exp1",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    subtasks: [
      { id: "subtask1", description: "Organize data files", completed: true },
      { id: "subtask2", description: "Draft initial findings", completed: true },
      { id: "subtask3", description: "Submit to team lead for review", completed: true },
    ],
  },
  {
    id: "t1",
    title: "Analyze blood samples for Project XYZ",
    description: "Run analysis on collected blood samples and record results",
    status: "pending",
    priority: "high",
    assigneeId: "3",
    experimentId: "exp1",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    subtasks: [
      { id: "subtask10", description: "Prepare testing equipment", completed: false },
      { id: "subtask11", description: "Process samples according to protocol", completed: false },
      { id: "subtask12", description: "Document findings in lab system", completed: false },
    ],
  },
  {
    id: "task-2",
    title: "Prepare cell cultures for experiment",
    description: "Set up cell cultures for next week's scheduled experiment",
    status: "in-progress",
    priority: "medium",
    assigneeId: "1",
    experimentId: "exp2",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    subtasks: [
      { id: "subtask4", description: "Prepare growth media", completed: true },
      { id: "subtask5", description: "Sterilize equipment", completed: true },
      { id: "subtask6", description: "Set up incubator conditions", completed: false },
    ],
  },
  {
    id: "t2",
    title: "Prepare cell cultures for experiment",
    description: "Set up cell cultures for next week's scheduled experiment",
    status: "in-progress",
    priority: "medium",
    assigneeId: "1",
    experimentId: "exp2",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    subtasks: [
      { id: "subtask4", description: "Prepare growth media", completed: true },
      { id: "subtask5", description: "Sterilize equipment", completed: true },
      { id: "subtask6", description: "Set up incubator conditions", completed: false },
    ],
  },
  {
    id: "task-3",
    title: "Set up equipment for microscopy",
    description: "Configure and calibrate microscope for scheduled imaging session",
    status: "in-progress",
    priority: "high",
    assigneeId: "3",
    experimentId: "exp3",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    subtasks: [
      { id: "subtask7", description: "Clean optical components", completed: true },
      { id: "subtask8", description: "Run calibration protocol", completed: false },
      { id: "subtask9", description: "Test with standard samples", completed: false },
    ],
  },
  {
    id: "t3",
    title: "Document experiment results",
    description: "Complete documentation for recent experiment findings",
    status: "completed",
    priority: "low",
    assigneeId: "2",
    experimentId: "exp1",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    subtasks: [
      { id: "subtask13", description: "Review documentation", completed: true },
      { id: "subtask14", description: "Update findings", completed: true },
      { id: "subtask15", description: "Final submission", completed: true },
    ],
  }
]